### ISSUE TITLE
Fish Shell: Error: Failed to execute 'convert' command

### ISSUE THREAD

**Issue by Link-** [icholy/ttygif#53]
Running `ttygif test` on Ubuntu `Linux vm 4.2.0-30-generic #36~14.04.1-Ubuntu SMP Fri Feb 26 18:49:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` and running the `fish` shell.
```
Creating Animated GIF ... this can take a while
Killed
Error: Failed to execute 'convert' command⏎ 
```
Tried to update dependencies and still getting the error.
```
> sudo apt-get install imagemagick ttyrec gcc x11-apps -u
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
x11-apps is already the newest version.
ttyrec is already the newest version.
imagemagick is already the newest version.
```

**Comment by icholy** [comment]
Can you pull master and try again? I just pushed some changes which should show the actual error.

**Comment by Link-** [comment]
Hey @icholy I've pulled the latest from `master` and still got the same error, no extra information

```
remote: Counting objects: 10, done.
remote: Total 10 (delta 6), reused 6 (delta 6), pack-reused 4
Unpacking objects: 100% (10/10), done.
From https://github.com/icholy/ttygif
 * branch            master     -> FETCH_HEAD
   43ef5e7..885f01a  master     -> origin/master
Updating 43ef5e7..885f01a
Fast-forward
 ttygif.c |  2 +-
 utils.c  | 15 +++++++++++++++
 utils.h  |  1 +
 3 files changed, 17 insertions(+), 1 deletion(-)
```

```
Creating Animated GIF ... this can take a while
Killed
Error: Failed to execute 'convert' command⏎
```

**Comment by icholy** [comment]
Can you go into https://github.com/icholy/ttygif/blob/885f01a6c5bc879fcdbd8d71633b3fa82069e9a7/ttygif.c#L248 and print out the command it's trying to run? 

``` c
printf("%s\n", sb->s);
```

**Comment by icholy** [comment]
@Link- actually I just pushed another change. It wasn't redirecting stderr. Try that first.

**Comment by Link-** [comment]
I pulled the latest and rebuilt the project and installed the new version but it's still not printing out a verbose error message. I found out the problem though. I'm using `fish` shell, when I recorded a new session using `bash` everything worked ok.

**Comment by icholy** [comment]
ok, let's leave it open then.

**Comment by icholy** [comment]
Works fine in fish for me :/

**Comment by icholy** [comment]
Do you have a minimal ttyrec recording that I can try?

**Comment by Link-** [comment]
Here's one that actually failed again right now. I'm starting to wonder whether it's the recording itself that's make the conversion fail or something else...

[ud_setup_manual.zip](https://github.com/icholy/ttygif/files/325825/ud_setup_manual.zip)

**Comment by icholy** [comment]
Worked fine for me in zsh and fish. Can you post the output of `convert -version` ?

**Comment by Link-** [comment]
That's very strange!

```
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP   
```

**Comment by atomantic** [comment]
I'm getting the same error on zsh:

```
Error: Failed to take snapshot: Undefined error: 0
Creating Animated GIF ... this can take a while
convert: no images defined `tty.gif' @ error/convert.c/ConvertImageCommand/3257.
Error: Failed to execute 'convert' command: Undefined error: 0
Created: tty.gif in the current directory!
```

convert -version
```
Version: ImageMagick 6.9.4-6 Q16 x86_64 2016-06-02 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

**Comment by icholy** [comment]
@atomantic looks like a different error, can you open a separate issue?

**Comment by icholy** [comment]
I just pushed a new version with the ability to print the commands being executed. Pull & build the latest master and set the `TTYGIF_DEBUG` env variable.

```
export TTYGIF_DEBUG=1
```

Try to run the `convert` command that gets logged.

**Comment by Link-** [comment]
`
...
convert.im6: unable to open image `/tmp/ttygif.j4VO54/809.xwd': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open image `/tmp/ttygif.j4VO54/810.xwd': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open image `/tmp/ttygif.j4VO54/811.xwd': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: unable to open image `/tmp/ttygif.j4VO54/812.xwd': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: no images defined `tty.gif' @ error/convert.c/ConvertImageCommand/3044.
`

**Comment by icholy** [comment]
Did you try running one of the xwd commands and seeing if the images get created?

**Comment by Link-** [comment]
An image of the current open terminal gets created yes.

**Comment by icholy** [comment]
That's weird. Those are the exact commands that it's running. So when you run them directly in the shell, the image gets created, but when when ttygif runs them they don't work. I'm not sure how to debug this.

**Comment by icholy** [comment]
try it now

**Comment by Link-** [comment]
I personally give up.. I tested it with a simple recording it worked, tested again with the one I want it failed.. 

```
Creating Animated GIF ... this can take a while
Killed
failed to execute: convert -loop 0  -delay 0.300000 /tmp/ttygif.Jm7n5X/0.xwd -delay 1.000000 /tmp/ttygif.Jm7n5X/1.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/7.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/13.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/18.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/24.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/30.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/36.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/42.xwd -delay 156.900000 /tmp/ttygif.Jm7n5X/47.xwd -delay 6.100000 /tmp/ttygif.Jm7n5X/50.xwd -delay 10.300000 /tmp/ttygif.Jm7n5X/51.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/53.xwd -delay 15.000000 /tmp/ttygif.Jm7n5X/54.xwd -delay 4.200000 /tmp/ttygif.Jm7n5X/55.xwd -delay 19.500000 /tmp/ttygif.Jm7n5X/56.xwd -delay 9.000000 /tmp/ttygif.Jm7n5X/57.xwd -delay 9.100000 /tmp/ttygif.Jm7n5X/58.xwd -delay 8.800000 /tmp/ttygif.Jm7n5X/59.xwd -delay 107.900000 /tmp/ttygif.Jm7n5X/61.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/62.xwd -delay 13.400000 /tmp/ttygif.Jm7n5X/63.xwd -delay 9.000000 /tmp/ttygif.Jm7n5X/64.xwd -delay 14.900000 /tmp/ttygif.Jm7n5X/65.xwd -delay 17.800000 /tmp/ttygif.Jm7n5X/66.xwd -delay 22.500000 /tmp/ttygif.Jm7n5X/67.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/68.xwd -delay 19.400000 /tmp/ttygif.Jm7n5X/69.xwd -delay 10.400000 /tmp/ttygif.Jm7n5X/70.xwd -delay 12.000000 /tmp/ttygif.Jm7n5X/71.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/72.xwd -delay 8.900000 /tmp/ttygif.Jm7n5X/73.xwd -delay 9.000000 /tmp/ttygif.Jm7n5X/74.xwd -delay 23.900000 /tmp/ttygif.Jm7n5X/75.xwd -delay 13.500000 /tmp/ttygif.Jm7n5X/76.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/77.xwd -delay 5.900000 /tmp/ttygif.Jm7n5X/78.xwd -delay 44.900000 /tmp/ttygif.Jm7n5X/79.xwd -delay 38.900000 /tmp/ttygif.Jm7n5X/80.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/81.xwd -delay 29.700000 /tmp/ttygif.Jm7n5X/82.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/83.xwd -delay 13.500000 /tmp/ttygif.Jm7n5X/84.xwd -delay 23.900000 /tmp/ttygif.Jm7n5X/85.xwd -delay 50.900000 /tmp/ttygif.Jm7n5X/86.xwd -delay 54.000000 /tmp/ttygif.Jm7n5X/87.xwd -delay 0.900000 /tmp/ttygif.Jm7n5X/88.xwd -delay 593.100000 /tmp/ttygif.Jm7n5X/89.xwd -delay 26.000000 /tmp/ttygif.Jm7n5X/91.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/97.xwd -delay 3.100000 /tmp/ttygif.Jm7n5X/98.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/99.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/105.xwd -delay 16.900000 /tmp/ttygif.Jm7n5X/111.xwd -delay 1.800000 /tmp/ttygif.Jm7n5X/112.xwd -delay 47.900000 /tmp/ttygif.Jm7n5X/113.xwd -delay 1.100000 /tmp/ttygif.Jm7n5X/116.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/118.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/120.xwd -delay 2.800000 /tmp/ttygif.Jm7n5X/124.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/130.xwd -delay 2.300000 /tmp/ttygif.Jm7n5X/132.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/138.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/142.xwd -delay 0.900000 /tmp/ttygif.Jm7n5X/143.xwd -delay 2.400000 /tmp/ttygif.Jm7n5X/148.xwd -delay 2.400000 /tmp/ttygif.Jm7n5X/152.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/155.xwd -delay 1.500000 /tmp/ttygif.Jm7n5X/160.xwd -delay 15.300000 /tmp/ttygif.Jm7n5X/164.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/165.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/170.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/176.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/179.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/182.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/188.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/194.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/200.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/202.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/208.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/214.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/220.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/221.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/227.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/233.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/239.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/245.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/248.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/249.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/251.xwd -delay 477.600000 /tmp/ttygif.Jm7n5X/254.xwd -delay 7.400000 /tmp/ttygif.Jm7n5X/257.xwd -delay 7.400000 /tmp/ttygif.Jm7n5X/260.xwd -delay 19.500000 /tmp/ttygif.Jm7n5X/261.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/263.xwd -delay 5.700000 /tmp/ttygif.Jm7n5X/264.xwd -delay 9.000000 /tmp/ttygif.Jm7n5X/265.xwd -delay 8.900000 /tmp/ttygif.Jm7n5X/266.xwd -delay 72.000000 /tmp/ttygif.Jm7n5X/267.xwd -delay 25.400000 /tmp/ttygif.Jm7n5X/268.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/269.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/275.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/281.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/287.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/293.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/299.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/305.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/311.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/317.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/323.xwd -delay 90.600000 /tmp/ttygif.Jm7n5X/325.xwd -delay 7.400000 /tmp/ttygif.Jm7n5X/328.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/329.xwd -delay 5.800000 /tmp/ttygif.Jm7n5X/330.xwd -delay 8.900000 /tmp/ttygif.Jm7n5X/331.xwd -delay 9.000000 /tmp/ttygif.Jm7n5X/332.xwd -delay 6.000000 /tmp/ttygif.Jm7n5X/333.xwd -delay 8.900000 /tmp/ttygif.Jm7n5X/334.xwd -delay 14.900000 /tmp/ttygif.Jm7n5X/336.xwd -delay 5.900000 /tmp/ttygif.Jm7n5X/337.xwd -delay 7.400000 /tmp/ttygif.Jm7n5X/339.xwd -delay 4.400000 /tmp/ttygif.Jm7n5X/341.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/342.xwd -delay 15.000000 /tmp/ttygif.Jm7n5X/343.xwd -delay 10.400000 /tmp/ttygif.Jm7n5X/344.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/345.xwd -delay 13.400000 /tmp/ttygif.Jm7n5X/346.xwd -delay 27.000000 /tmp/ttygif.Jm7n5X/347.xwd -delay 9.600000 /tmp/ttygif.Jm7n5X/348.xwd -delay 8.000000 /tmp/ttygif.Jm7n5X/349.xwd -delay 116.400000 /tmp/ttygif.Jm7n5X/350.xwd -delay 2355.000000 /tmp/ttygif.Jm7n5X/351.xwd -delay 0.700000 /tmp/ttygif.Jm7n5X/352.xwd -delay 217.700000 /tmp/ttygif.Jm7n5X/353.xwd -delay 18.300000 /tmp/ttygif.Jm7n5X/357.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/359.xwd -delay 1.400000 /tmp/ttygif.Jm7n5X/363.xwd -delay 1.100000 /tmp/ttygif.Jm7n5X/365.xwd -delay 13.400000 /tmp/ttygif.Jm7n5X/367.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/369.xwd -delay 0.700000 /tmp/ttygif.Jm7n5X/371.xwd -delay 2.900000 /tmp/ttygif.Jm7n5X/373.xwd -delay 2.200000 /tmp/ttygif.Jm7n5X/374.xwd -delay 4.300000 /tmp/ttygif.Jm7n5X/377.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/378.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/380.xwd -delay 250.500000 /tmp/ttygif.Jm7n5X/381.xwd -delay 1.800000 /tmp/ttygif.Jm7n5X/385.xwd -delay 18.000000 /tmp/ttygif.Jm7n5X/387.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/389.xwd -delay 2.500000 /tmp/ttygif.Jm7n5X/392.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/393.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/395.xwd -delay 207.000000 /tmp/ttygif.Jm7n5X/396.xwd -delay 1.000000 /tmp/ttygif.Jm7n5X/400.xwd -delay 18.700000 /tmp/ttygif.Jm7n5X/402.xwd -delay 3.200000 /tmp/ttygif.Jm7n5X/404.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/406.xwd -delay 2.900000 /tmp/ttygif.Jm7n5X/409.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/410.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/412.xwd -delay 254.600000 /tmp/ttygif.Jm7n5X/413.xwd -delay 1.800000 /tmp/ttygif.Jm7n5X/417.xwd -delay 17.100000 /tmp/ttygif.Jm7n5X/419.xwd -delay 0.900000 /tmp/ttygif.Jm7n5X/421.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/423.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/425.xwd -delay 16.500000 /tmp/ttygif.Jm7n5X/427.xwd -delay 3.900000 /tmp/ttygif.Jm7n5X/429.xwd -delay 1.100000 /tmp/ttygif.Jm7n5X/431.xwd -delay 1.300000 /tmp/ttygif.Jm7n5X/433.xwd -delay 1.100000 /tmp/ttygif.Jm7n5X/435.xwd -delay 1.900000 /tmp/ttygif.Jm7n5X/437.xwd -delay 7.400000 /tmp/ttygif.Jm7n5X/438.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/439.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/440.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/442.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/444.xwd -delay 5.200000 /tmp/ttygif.Jm7n5X/447.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/448.xwd -delay 0.700000 /tmp/ttygif.Jm7n5X/449.xwd -delay 2.500000 /tmp/ttygif.Jm7n5X/450.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/451.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/453.xwd -delay 1.600000 /tmp/ttygif.Jm7n5X/455.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/456.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/458.xwd -delay 3.200000 /tmp/ttygif.Jm7n5X/460.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/461.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/462.xwd -delay 2.500000 /tmp/ttygif.Jm7n5X/463.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/464.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/465.xwd -delay 2.400000 /tmp/ttygif.Jm7n5X/466.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/467.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/468.xwd -delay 224.100000 /tmp/ttygif.Jm7n5X/469.xwd -delay 20.300000 /tmp/ttygif.Jm7n5X/473.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/475.xwd -delay 15.700000 /tmp/ttygif.Jm7n5X/477.xwd -delay 1.400000 /tmp/ttygif.Jm7n5X/479.xwd -delay 4.100000 /tmp/ttygif.Jm7n5X/481.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/483.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/485.xwd -delay 10.800000 /tmp/ttygif.Jm7n5X/487.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/488.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/489.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/490.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/491.xwd -delay 2.800000 /tmp/ttygif.Jm7n5X/492.xwd -delay 0.800000 /tmp/ttygif.Jm7n5X/493.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/494.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/495.xwd -delay 9.300000 /tmp/ttygif.Jm7n5X/496.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/497.xwd -delay 1.100000 /tmp/ttygif.Jm7n5X/498.xwd -delay 0.800000 /tmp/ttygif.Jm7n5X/499.xwd -delay 9.900000 /tmp/ttygif.Jm7n5X/502.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/503.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/504.xwd -delay 2.700000 /tmp/ttygif.Jm7n5X/505.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/506.xwd -delay 1402.900000 /tmp/ttygif.Jm7n5X/508.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/509.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/510.xwd -delay 2.800000 /tmp/ttygif.Jm7n5X/511.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/512.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/513.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/514.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/515.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/516.xwd -delay 2.200000 /tmp/ttygif.Jm7n5X/517.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/518.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/520.xwd -delay 2.100000 /tmp/ttygif.Jm7n5X/522.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/523.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/524.xwd -delay 2.100000 /tmp/ttygif.Jm7n5X/525.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/526.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/527.xwd -delay 1.600000 /tmp/ttygif.Jm7n5X/528.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/529.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/530.xwd -delay 1.900000 /tmp/ttygif.Jm7n5X/531.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/532.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/533.xwd -delay 2.100000 /tmp/ttygif.Jm7n5X/534.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/535.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/536.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/537.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/538.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/540.xwd -delay 2.200000 /tmp/ttygif.Jm7n5X/542.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/543.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/545.xwd -delay 1.900000 /tmp/ttygif.Jm7n5X/547.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/548.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/550.xwd -delay 5.500000 /tmp/ttygif.Jm7n5X/552.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/553.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/555.xwd -delay 1.700000 /tmp/ttygif.Jm7n5X/557.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/558.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/560.xwd -delay 2.500000 /tmp/ttygif.Jm7n5X/562.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/563.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/565.xwd -delay 2.300000 /tmp/ttygif.Jm7n5X/567.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/568.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/570.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/572.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/573.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/575.xwd -delay 6.100000 /tmp/ttygif.Jm7n5X/577.xwd -delay 0.400000 /tmp/ttygif.Jm7n5X/578.xwd -delay 0.700000 /tmp/ttygif.Jm7n5X/579.xwd -delay 2.900000 /tmp/ttygif.Jm7n5X/580.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/581.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/582.xwd -delay 2.000000 /tmp/ttygif.Jm7n5X/583.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/584.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/586.xwd -delay 3.100000 /tmp/ttygif.Jm7n5X/588.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/589.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/591.xwd -delay 4.100000 /tmp/ttygif.Jm7n5X/593.xwd -delay 0.800000 /tmp/ttygif.Jm7n5X/594.xwd -delay 0.300000 /tmp/ttygif.Jm7n5X/596.xwd -delay 6.100000 /tmp/ttygif.Jm7n5X/598.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/599.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/601.xwd -delay 2.300000 /tmp/ttygif.Jm7n5X/603.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/604.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/606.xwd -delay 15.800000 /tmp/ttygif.Jm7n5X/608.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/609.xwd -delay 0.500000 /tmp/ttygif.Jm7n5X/611.xwd -delay 4.800000 /tmp/ttygif.Jm7n5X/613.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/614.xwd -delay 0.900000 /tmp/ttygif.Jm7n5X/616.xwd -delay 13.000000 /tmp/ttygif.Jm7n5X/618.xwd -delay 105.600000 /tmp/ttygif.Jm7n5X/619.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/620.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/621.xwd -delay 6.000000 /tmp/ttygif.Jm7n5X/622.xwd -delay 40.500000 /tmp/ttygif.Jm7n5X/626.xwd -delay 548.300000 /tmp/ttygif.Jm7n5X/630.xwd -delay 0.200000 /tmp/ttygif.Jm7n5X/631.xwd -delay 1.000000 /tmp/ttygif.Jm7n5X/632.xwd -delay 18.100000 /tmp/ttygif.Jm7n5X/633.xwd -delay 45.000000 /tmp/ttygif.Jm7n5X/634.xwd -delay 11.900000 /tmp/ttygif.Jm7n5X/635.xwd -delay 0.600000 /tmp/ttygif.Jm7n5X/636.xwd -delay 11.400000 /tmp/ttygif.Jm7n5X/637.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/638.xwd -delay 52.400000 /tmp/ttygif.Jm7n5X/639.xwd -delay 12.000000 /tmp/ttygif.Jm7n5X/640.xwd -delay 30.000000 /tmp/ttygif.Jm7n5X/641.xwd -delay 26.900000 /tmp/ttygif.Jm7n5X/642.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/643.xwd -delay 4.600000 /tmp/ttygif.Jm7n5X/644.xwd -delay 11.800000 /tmp/ttygif.Jm7n5X/645.xwd -delay 10.300000 /tmp/ttygif.Jm7n5X/646.xwd -delay 28.500000 /tmp/ttygif.Jm7n5X/647.xwd -delay 28.400000 /tmp/ttygif.Jm7n5X/648.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/649.xwd -delay 2.800000 /tmp/ttygif.Jm7n5X/650.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/651.xwd -delay 2.400000 /tmp/ttygif.Jm7n5X/652.xwd -delay 2.600000 /tmp/ttygif.Jm7n5X/653.xwd -delay 2.700000 /tmp/ttygif.Jm7n5X/654.xwd -delay 2.500000 /tmp/ttygif.Jm7n5X/655.xwd -delay 2.400000 /tmp/ttygif.Jm7n5X/656.xwd -delay 16.500000 /tmp/ttygif.Jm7n5X/657.xwd -delay 5.900000 /tmp/ttygif.Jm7n5X/660.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/661.xwd -delay 16.200000 /tmp/ttygif.Jm7n5X/662.xwd -delay 53.900000 /tmp/ttygif.Jm7n5X/663.xwd -delay 10.500000 /tmp/ttygif.Jm7n5X/664.xwd -delay 0.100000 /tmp/ttygif.Jm7n5X/665.xwd -delay 11.800000 /tmp/ttygif.Jm7n5X/666.xwd -delay 26.900000 /tmp/ttygif.Jm7n5X/667.xwd -delay 13.500000 /tmp/ttygif.Jm7n5X/668.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/669.xwd -delay 11.900000 /tmp/ttygif.Jm7n5X/670.xwd -delay 7.500000 /tmp/ttygif.Jm7n5X/671.xwd -delay 13.500000 /tmp/ttygif.Jm7n5X/672.xwd -delay 24.000000 /tmp/ttygif.Jm7n5X/673.xwd -delay 49.400000 /tmp/ttygif.Jm7n5X/675.xwd -delay 7.300000 /tmp/ttygif.Jm7n5X/676.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/682.xwd -delay 10.900000 /tmp/ttygif.Jm7n5X/684.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/690.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/696.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/702.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/708.xwd -delay 1.400000 /tmp/ttygif.Jm7n5X/710.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/716.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/722.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/728.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/734.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/740.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/746.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/752.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/758.xwd -delay 0.000000 /tmp/ttygif.Jm7n5X/764.xwd -delay 1013.700000 /tmp/ttygif.Jm7n5X/766.xwd -layers Optimize tty.gif 2>&1
```

[ubersetup.zip](https://github.com/icholy/ttygif/files/355102/ubersetup.zip)

**Comment by icholy** [comment]
kk
